insert into public.ipl_teams (name, short_code, primary_color, secondary_color)
values
  ('Chennai Super Kings', 'CSK', '#E9530D', '#2B5DA8'),
  ('Delhi Capitals', 'DC', '#2561AE', '#282968'),
  ('Gujarat Titans', 'GT', '#1B2133', '#DBBE6E'),
  ('Kolkata Knight Riders', 'KKR', '#3A225D', '#F7D54E'),
  ('Lucknow Super Giants', 'LSG', '#0057E2', '#F28B00'),
  ('Mumbai Indians', 'MI', '#004B8D', '#FFD141'),
  ('Punjab Kings', 'PBKS', '#DD1F2D', '#F2D1A0'),
  ('Rajasthan Royals', 'RR', '#EA1A85', '#0E4D92'),
  ('Royal Challengers Bengaluru', 'RCB', '#D71921', '#000000'),
  ('Sunrisers Hyderabad', 'SRH', '#EE7429', '#FCCB11')
on conflict (short_code) do update
set
  name = excluded.name,
  primary_color = excluded.primary_color,
  secondary_color = excluded.secondary_color;

insert into public.auction_teams (team_name, owner_name)
values
  ('Ainesh', 'Ainesh'),
  ('D-A', 'D-A'),
  ('PI', 'PI'),
  ('R-A', 'R-A'),
  ('A-I', 'A-I')
on conflict (team_name) do update
set owner_name = excluded.owner_name;

delete from public.players;

with players_seed (player_name, player_role, auction_team_name, ipl_short_code) as (
  values
    ('Sanju Samson', 'TBD', 'Ainesh', 'CSK'),
    ('Noor Ahmad', 'TBD', 'Ainesh', 'CSK'),
    ('Dewald Brevis', 'TBD', 'Ainesh', 'CSK'),
    ('Mukesh Choudhury', 'TBD', 'Ainesh', 'CSK'),
    ('Matt Short', 'TBD', 'Ainesh', 'CSK'),
    ('Spencer Johnson', 'TBD', 'Ainesh', 'CSK'),
    ('Karthik Sharma', 'TBD', 'Ainesh', 'CSK'),
    ('Matt Henry', 'TBD', 'Ainesh', 'CSK'),
    ('MS Dhoni', 'TBD', 'Ainesh', 'CSK'),
    ('Shreyas Gopal', 'TBD', 'Ainesh', 'CSK'),
    ('Aman Khan', 'TBD', 'Ainesh', 'CSK'),
    ('Shivam Dube', 'TBD', 'D-A', 'CSK'),
    ('Anshul Kamboj', 'TBD', 'D-A', 'CSK'),
    ('Urvil Patel', 'TBD', 'D-A', 'CSK'),
    ('Ayush Mhatre', 'TBD', 'PI', 'CSK'),
    ('Akeal Hosein', 'TBD', 'PI', 'CSK'),
    ('Sarfaraz Khan', 'TBD', 'R-A', 'CSK'),
    ('Rahul Chahar', 'TBD', 'R-A', 'CSK'),
    ('Zak Foulkes', 'TBD', 'R-A', 'CSK'),
    ('Gurjapneet Singh', 'TBD', 'R-A', 'CSK'),
    ('Jamie Overton', 'TBD', 'R-A', 'CSK'),
    ('Ruturaj Gaikwad', 'TBD', 'A-I', 'CSK'),
    ('Khaleel Ahmed', 'TBD', 'A-I', 'CSK'),
    ('Prashant Veer', 'TBD', 'A-I', 'CSK'),
    ('Ramakrishna Ghosh', 'TBD', 'A-I', 'CSK'),
    ('Mitchell Starc', 'TBD', 'Ainesh', 'DC'),
    ('Ashutosh Sharma', 'TBD', 'Ainesh', 'DC'),
    ('Dushmantha Chameera', 'TBD', 'Ainesh', 'DC'),
    ('Karun Nair', 'TBD', 'Ainesh', 'DC'),
    ('David Miller', 'TBD', 'Ainesh', 'DC'),
    ('KL Rahul (C)', 'TBD', 'D-A', 'DC'),
    ('Kuldeep Yadav', 'TBD', 'D-A', 'DC'),
    ('Aaqib Nabi', 'TBD', 'D-A', 'DC'),
    ('Axar Patel', 'TBD', 'PI', 'DC'),
    ('Madhav Tiwari', 'TBD', 'PI', 'DC'),
    ('Pathum Nissanka', 'TBD', 'PI', 'DC'),
    ('T Natarajan', 'TBD', 'PI', 'DC'),
    ('Vipraj Nigam', 'TBD', 'PI', 'DC'),
    ('Tripurana Vijay', 'TBD', 'PI', 'DC'),
    ('Tristan Stubbs', 'TBD', 'R-A', 'DC'),
    ('Nitish Rana', 'TBD', 'R-A', 'DC'),
    ('Lungi Ngidi', 'TBD', 'R-A', 'DC'),
    ('Prithvi Shaw', 'TBD', 'R-A', 'DC'),
    ('Sameer Rizvi', 'TBD', 'R-A', 'DC'),
    ('Kyle Jamieson', 'TBD', 'R-A', 'DC'),
    ('Abhishek Porel', 'TBD', 'R-A', 'DC'),
    ('Mukesh Kumar', 'TBD', 'A-I', 'DC'),
    ('Ben Duckett', 'TBD', 'A-I', 'DC'),
    ('Ajay Mandal', 'TBD', 'A-I', 'DC'),
    ('Sahil Parakh', 'TBD', 'A-I', 'DC'),
    ('Jos Buttler (RTM)', 'TBD', 'Ainesh', 'GT'),
    ('Prasidh Krishna', 'TBD', 'Ainesh', 'GT'),
    ('Glenn Phillips', 'TBD', 'Ainesh', 'GT'),
    ('Jayant Yadav', 'TBD', 'Ainesh', 'GT'),
    ('Washington Sundar', 'TBD', 'Ainesh', 'GT'),
    ('Rashid Khan', 'TBD', 'D-A', 'GT'),
    ('Manav Suthar', 'TBD', 'D-A', 'GT'),
    ('R Sai Kishore', 'TBD', 'D-A', 'GT'),
    ('Kagiso Rabada', 'TBD', 'PI', 'GT'),
    ('Shah Rukh Khan', 'TBD', 'PI', 'GT'),
    ('Kulwant Khejroliya', 'TBD', 'PI', 'GT'),
    ('Mohammad Siraj', 'TBD', 'PI', 'GT'),
    ('Arshad Khan', 'TBD', 'PI', 'GT'),
    ('Sai Sudharshan (C)', 'TBD', 'R-A', 'GT'),
    ('Ishant Sharma', 'TBD', 'R-A', 'GT'),
    ('Rahul Tewatia', 'TBD', 'R-A', 'GT'),
    ('Anuj Rawaj', 'TBD', 'R-A', 'GT'),
    ('Nishant Sindhu', 'TBD', 'R-A', 'GT'),
    ('Tom Banton', 'TBD', 'R-A', 'GT'),
    ('Luke Wood', 'TBD', 'R-A', 'GT'),
    ('Jason Holder', 'TBD', 'R-A', 'GT'),
    ('Gurnoor Brar', 'TBD', 'R-A', 'GT'),
    ('Shubman Gill (C)', 'TBD', 'A-I', 'GT'),
    ('Ashok Sharma', 'TBD', 'A-I', 'GT'),
    ('Kumar Kushagra', 'TBD', 'A-I', 'GT'),
    ('Rovman Powell', 'TBD', 'Ainesh', 'KKR'),
    ('Umran Malik', 'TBD', 'Ainesh', 'KKR'),
    ('Saurabh Dubey', 'TBD', 'Ainesh', 'KKR'),
    ('Rahul Tripathi', 'TBD', 'Ainesh', 'KKR'),
    ('Karthik Tyagi', 'TBD', 'Ainesh', 'KKR'),
    ('Sarthak Ranjan', 'TBD', 'Ainesh', 'KKR'),
    ('Varun Chakravarthy', 'TBD', 'D-A', 'KKR'),
    ('Navdeep Saini', 'TBD', 'D-A', 'KKR'),
    ('Manish Pandey', 'TBD', 'D-A', 'KKR'),
    ('Rachin Ravindra', 'TBD', 'D-A', 'KKR'),
    ('Sunil Narine', 'TBD', 'PI', 'KKR'),
    ('Matheesha Pathirana', 'TBD', 'PI', 'KKR'),
    ('Finn Allen', 'TBD', 'PI', 'KKR'),
    ('Vaibhav Arora', 'TBD', 'PI', 'KKR'),
    ('Rinku Singh', 'TBD', 'PI', 'KKR'),
    ('Blessing Muzarabani', 'TBD', 'PI', 'KKR'),
    ('Ramandeep Singh', 'TBD', 'PI', 'KKR'),
    ('Angkrish Raghuvanshi', 'TBD', 'PI', 'KKR'),
    ('Prashant Solanki', 'TBD', 'PI', 'KKR'),
    ('Daksh Kamra', 'TBD', 'PI', 'KKR'),
    ('Cameron Green (VC)', 'TBD', 'R-A', 'KKR'),
    ('Anukul Roy', 'TBD', 'R-A', 'KKR'),
    ('Ajinkya Rahane', 'TBD', 'A-I', 'KKR'),
    ('Tejasvi Dahiya', 'TBD', 'A-I', 'KKR'),
    ('Tim Seifert', 'TBD', 'A-I', 'KKR'),
    ('Abdul Samad', 'TBD', 'Ainesh', 'LSG'),
    ('Matthew Breetzke', 'TBD', 'Ainesh', 'LSG'),
    ('Nicholas Pooran', 'TBD', 'D-A', 'LSG'),
    ('Mohammad Shami', 'TBD', 'D-A', 'LSG'),
    ('Wanindu Hasaranga', 'TBD', 'D-A', 'LSG'),
    ('Aiden Markram (C)', 'TBD', 'PI', 'LSG'),
    ('Himmat Singh', 'TBD', 'PI', 'LSG'),
    ('Josh Inglis', 'TBD', 'PI', 'LSG'),
    ('Mayank Yadav', 'TBD', 'PI', 'LSG'),
    ('Avesh Khan', 'TBD', 'PI', 'LSG'),
    ('M Siddharth', 'TBD', 'PI', 'LSG'),
    ('Mohsin Khan', 'TBD', 'PI', 'LSG'),
    ('Anrich Nortje', 'TBD', 'PI', 'LSG'),
    ('Akshat Raghuwanshi', 'TBD', 'PI', 'LSG'),
    ('Rishabh Pant', 'TBD', 'R-A', 'LSG'),
    ('Ayush Badoni', 'TBD', 'R-A', 'LSG'),
    ('Shahbaz Ahmed', 'TBD', 'R-A', 'LSG'),
    ('Arshin Kulkarni', 'TBD', 'R-A', 'LSG'),
    ('Digvesh Rathi', 'TBD', 'R-A', 'LSG'),
    ('Arjun Tendulkar', 'TBD', 'R-A', 'LSG'),
    ('Akash Singh', 'TBD', 'R-A', 'LSG'),
    ('Mitchell Marsh', 'TBD', 'A-I', 'LSG'),
    ('Mukul Choudhary', 'TBD', 'A-I', 'LSG'),
    ('Prince Yadav', 'TBD', 'A-I', 'LSG'),
    ('Naman Tiwari', 'TBD', 'A-I', 'LSG'),
    ('Will Jacks', 'TBD', 'Ainesh', 'MI'),
    ('Mayank Markhande', 'TBD', 'Ainesh', 'MI'),
    ('Ryan Rickelton', 'TBD', 'Ainesh', 'MI'),
    ('Robin Minz', 'TBD', 'Ainesh', 'MI'),
    ('Raj Angad Bawa', 'TBD', 'Ainesh', 'MI'),
    ('Jasprit Bumrah (VC)', 'TBD', 'D-A', 'MI'),
    ('Shardul Thakur', 'TBD', 'D-A', 'MI'),
    ('Ashwani Kumar', 'TBD', 'D-A', 'MI'),
    ('Sherfane Rutherford', 'TBD', 'D-A', 'MI'),
    ('Suryakumar Yadav', 'TBD', 'PI', 'MI'),
    ('Rohit Sharma', 'TBD', 'PI', 'MI'),
    ('Deepak Chahar', 'TBD', 'PI', 'MI'),
    ('Danish Malewar', 'TBD', 'PI', 'MI'),
    ('Hardik Pandya', 'TBD', 'R-A', 'MI'),
    ('Trent Boult', 'TBD', 'R-A', 'MI'),
    ('Tilak Verma (RTM)', 'TBD', 'R-A', 'MI'),
    ('Raghu Sharma', 'TBD', 'R-A', 'MI'),
    ('Quinton de Kock', 'TBD', 'R-A', 'MI'),
    ('Naman Dhir', 'TBD', 'R-A', 'MI'),
    ('Mitchell Santner', 'TBD', 'R-A', 'MI'),
    ('Mohammad Izhar', 'TBD', 'R-A', 'MI'),
    ('Corbin Bosch', 'TBD', 'A-I', 'MI'),
    ('Allah Ghazanfar', 'TBD', 'A-I', 'MI'),
    ('Atharva Ankolekar', 'TBD', 'A-I', 'MI'),
    ('Mayank Rawat', 'TBD', 'A-I', 'MI'),
    ('Marcus Stoinis', 'TBD', 'Ainesh', 'PBKS'),
    ('Harpreet Brar', 'TBD', 'Ainesh', 'PBKS'),
    ('Arshdeep Singh (RTM)', 'TBD', 'D-A', 'PBKS'),
    ('Cooper Connolly', 'TBD', 'D-A', 'PBKS'),
    ('Priyansh Arya', 'TBD', 'D-A', 'PBKS'),
    ('Shashank Singh', 'TBD', 'D-A', 'PBKS'),
    ('Nehal Wadhera', 'TBD', 'PI', 'PBKS'),
    ('Azmatullah Omarzai', 'TBD', 'PI', 'PBKS'),
    ('Lockie Ferguson', 'TBD', 'PI', 'PBKS'),
    ('Musheer Khan', 'TBD', 'PI', 'PBKS'),
    ('Mitch Owen', 'TBD', 'PI', 'PBKS'),
    ('Vyshak Vijaykumar', 'TBD', 'PI', 'PBKS'),
    ('Pyla Avinash', 'TBD', 'PI', 'PBKS'),
    ('Marco Jansen', 'TBD', 'R-A', 'PBKS'),
    ('Suryansh Shedge', 'TBD', 'R-A', 'PBKS'),
    ('Ben Dwarshuis', 'TBD', 'R-A', 'PBKS'),
    ('Yash Thakur', 'TBD', 'R-A', 'PBKS'),
    ('Pravin Dubey', 'TBD', 'R-A', 'PBKS'),
    ('Vishnu Vinod', 'TBD', 'R-A', 'PBKS'),
    ('Vishal Nishad', 'TBD', 'R-A', 'PBKS'),
    ('Xavier Bartlett', 'TBD', 'R-A', 'PBKS'),
    ('Shreyas Iyer (RTM)', 'TBD', 'A-I', 'PBKS'),
    ('Prabhsimran Singh', 'TBD', 'A-I', 'PBKS'),
    ('Yuzvendra Chahal', 'TBD', 'A-I', 'PBKS'),
    ('Harnoor Pannu', 'TBD', 'A-I', 'PBKS'),
    ('Dhruv Jurel', 'TBD', 'Ainesh', 'RR'),
    ('Kuldeep Sen', 'TBD', 'Ainesh', 'RR'),
    ('Shimron Hetmyer', 'TBD', 'Ainesh', 'RR'),
    ('Ravindra Jadeja', 'TBD', 'D-A', 'RR'),
    ('Vaibhav Suryavanshi', 'TBD', 'D-A', 'RR'),
    ('Riyan Parag (RTM)', 'TBD', 'PI', 'RR'),
    ('Ravi Bishnoi', 'TBD', 'PI', 'RR'),
    ('Tushar Deshpande', 'TBD', 'PI', 'RR'),
    ('Nandre Burger', 'TBD', 'PI', 'RR'),
    ('Kwena Maphaka', 'TBD', 'PI', 'RR'),
    ('Yudhvir Singh', 'TBD', 'PI', 'RR'),
    ('Lhuan-Dre Pretorious', 'TBD', 'PI', 'RR'),
    ('Jofra Archer', 'TBD', 'R-A', 'RR'),
    ('Donovan Ferreira', 'TBD', 'R-A', 'RR'),
    ('Adam Milne', 'TBD', 'R-A', 'RR'),
    ('Shubham Dubey', 'TBD', 'R-A', 'RR'),
    ('Dasun Shanaka', 'TBD', 'R-A', 'RR'),
    ('Ravi Singh', 'TBD', 'R-A', 'RR'),
    ('Vignesh Puthur', 'TBD', 'R-A', 'RR'),
    ('Sushant Mishra', 'TBD', 'R-A', 'RR'),
    ('Yashasvi Jaiswal (VC)', 'TBD', 'A-I', 'RR'),
    ('Aman Rao', 'TBD', 'A-I', 'RR'),
    ('Sandeep Sharma', 'TBD', 'A-I', 'RR'),
    ('Yash Raj Punja', 'TBD', 'A-I', 'RR'),
    ('Virat Kohli (C)', 'TBD', 'Ainesh', 'RCB'),
    ('Swapnil Singh', 'TBD', 'Ainesh', 'RCB'),
    ('Nuwan Thushara', 'TBD', 'Ainesh', 'RCB'),
    ('Venkatesh Iyer', 'TBD', 'Ainesh', 'RCB'),
    ('Tim David', 'TBD', 'Ainesh', 'RCB'),
    ('Bhuvneshwar Kumar', 'TBD', 'D-A', 'RCB'),
    ('Suyash Sharma', 'TBD', 'D-A', 'RCB'),
    ('Kanishk Chohan', 'TBD', 'D-A', 'RCB'),
    ('Jitesh Sharma', 'TBD', 'D-A', 'RCB'),
    ('Vihaan Malhotra', 'TBD', 'D-A', 'RCB'),
    ('Jacob Duffy', 'TBD', 'D-A', 'RCB'),
    ('Rajat Patidar', 'TBD', 'PI', 'RCB'),
    ('Devdutt Padikkal', 'TBD', 'PI', 'RCB'),
    ('Rasikh Dar', 'TBD', 'PI', 'RCB'),
    ('Josh Hazlewood', 'TBD', 'R-A', 'RCB'),
    ('Krunal Pandya', 'TBD', 'R-A', 'RCB'),
    ('Satwik Deswal', 'TBD', 'R-A', 'RCB'),
    ('Jordan Cox', 'TBD', 'R-A', 'RCB'),
    ('Jacob Bethell', 'TBD', 'R-A', 'RCB'),
    ('Yash Dayal', 'TBD', 'R-A', 'RCB'),
    ('Abhinandan Singh', 'TBD', 'R-A', 'RCB'),
    ('Phil Salt', 'TBD', 'A-I', 'RCB'),
    ('Vicky Ostwal', 'TBD', 'A-I', 'RCB'),
    ('Mangesh Yadav', 'TBD', 'A-I', 'RCB'),
    ('Romario Shepherd', 'TBD', 'A-I', 'RCB'),
    ('Abhishek Sharma (VC)', 'TBD', 'Ainesh', 'SRH'),
    ('Liam Livingstone', 'TBD', 'Ainesh', 'SRH'),
    ('Heinrich Klaasen', 'TBD', 'D-A', 'SRH'),
    ('Shivam Mavi', 'TBD', 'D-A', 'SRH'),
    ('Nitish Kumar Reddy', 'TBD', 'D-A', 'SRH'),
    ('Travis Head (VC)', 'TBD', 'PI', 'SRH'),
    ('Harshal Patel', 'TBD', 'PI', 'SRH'),
    ('Harsh Dubey', 'TBD', 'PI', 'SRH'),
    ('Kamindu Mendis', 'TBD', 'PI', 'SRH'),
    ('Eshan Malinga', 'TBD', 'PI', 'SRH'),
    ('Brydon Carse', 'TBD', 'PI', 'SRH'),
    ('Pat Cummins', 'TBD', 'R-A', 'SRH'),
    ('Onkar Tukaram', 'TBD', 'R-A', 'SRH'),
    ('Amit Kumar', 'TBD', 'R-A', 'SRH'),
    ('Sakib Hussain', 'TBD', 'R-A', 'SRH'),
    ('Jaydev Unadkat', 'TBD', 'R-A', 'SRH'),
    ('Shivang Kumar', 'TBD', 'R-A', 'SRH'),
    ('Ishan Kishan', 'TBD', 'A-I', 'SRH'),
    ('Salil Arora', 'TBD', 'A-I', 'SRH'),
    ('Zeeshan Ansari', 'TBD', 'A-I', 'SRH'),
    ('Aniket Verma', 'TBD', 'A-I', 'SRH'),
    ('Krains Fuletra', 'TBD', 'A-I', 'SRH'),
    ('David Payne', 'TBD', 'A-I', 'SRH'),
    ('R Smaran', 'TBD', 'A-I', 'SRH'),
    ('Praful Hinge', 'TBD', 'A-I', 'SRH')
)
insert into public.players (player_name, player_role, auction_team_id, ipl_team_id)
select
  s.player_name,
  s.player_role,
  at.id,
  it.id
from players_seed s
join public.auction_teams at on at.team_name = s.auction_team_name
join public.ipl_teams it on it.short_code = s.ipl_short_code;
